TEXT_REPLACEMENTS = {
    '/': '&',
    '[': '(',
    ']': ')'
}

CONDITION_TYPE = {
    'ReleaseTitleSpecification': 'release_title',
    'ReleaseGroupSpecification': 'release_group',
    'LanguageSpecification': 'language',
    'SourceSpecification': 'source'
}

SOURCE_TYPE = {
    'Bluray': 'bluray',
    'Bluray Remux': 'bluray_raw',
    'Remux': 'raw',
    'DVD': 'dvd',
    'WEB': 'web_dl',
    'WEBDL': 'web_dl',
    'WEBRIP': 'webrip'
}

# TODO: Might need to have separate constants for Radarr and Sonarr, using Sonarr for now
LANGUAGE = {
    "unknown": 0,
    "english": 1,
    "french": 2,
    "spanish": 3,
    "german": 4,
    "italian": 5,
    "danish": 6,
    "dutch": 7,
    "japanese": 8,
    "icelandic": 9,
    "chinese": 10,
    "russian": 11,
    "polish": 12,
    "vietnamese": 13,
    "swedish": 14,
    "norwegian": 15,
    "finnish": 16,
    "turkish": 17,
    "portuguese": 18,
    "flemish": 19,
    "greek": 20,
    "korean": 21,
    "hungarian": 22,
    "hebrew": 23,
    "lithuanian": 24,
    "czech": 25,
    "arabic": 26,
    "hindi": 27,
    "bulgarian": 28,
    "malayalam": 29,
    "ukrainian": 30,
    "slovak": 31,
    "thai": 32,
    "portuguese_br": 33,
    "spanish_latino": 34,
    "romanian": 35,
    "latvian": 36,
    "persian": 37,
    "catalan": 38,
    "croatian": 39,
    "serbian": 40,
    "bosnian": 41,
    "estonian": 42,
    "tamil": 43,
    "indonesian": 44,
    "macedonian": 45,
    "slovenian": 46,
    "original": -2
}

QUALITIES = {
    "Raw-HD": 1,
    "BR-Disk": 2,
    "Remux-2160p": 3,
    "Bluray-2160p": 4,
    "WEBDL-2160p": 5,
    "WEBRip-2160p": 6,
    "HDTV-2160p": 7,
    "Remux-1080p": 8,
    "WEBDL-1080p": 9,
    "Bluray-1080p": 10,
    "WEBRip-1080p": 11,
    "HDTV-1080p": 12,
    "Bluray-720p": 13,
    "WEBDL-720p": 14,
    "WEBRip-720p": 15,
    "HDTV-720p": 16,
    "Bluray-576p": 17,
    "Bluray-480p": 18,
    "WEBDL-480p": 19,
    "WEBRip-480p": 20,
    "DVD-R": 21,
    "DVD": 22,
    "DVDSCR": 23,
    "SDTV": 24,
    "Telecine": 25,
    "Telesync": 26,
    "REGIONAL": 27,
    "WORKPRINT": 28,
    "CAM": 29,
    "Unknown": 30
}