name: Sync with Dictionarry
permissions:
  contents: write
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
      - name: Add Dictionarry connection
        run: |
          git remote add upstream https://github.com/Dictionarry-Hub/database.git
          git fetch upstream
      - name: Update repository
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git checkout main
          git checkout upstream/stable -- . ':(exclude).github/workflows/'
      - name: Show changed files
        run: |
          if ! git diff --quiet; then
            echo "===== FILES CHANGED ====="
            echo ""
            echo "Added files:"
            git diff --diff-filter=A --name-only || echo "None"
            echo ""
            echo "Modified files:"
            git diff --diff-filter=M --name-only || echo "None"
            echo ""
            echo "Deleted files:"
            git diff --diff-filter=D --name-only || echo "None"
            echo ""
            echo "===== DETAILED CHANGES ====="
            git --no-pager diff
          else
            echo "No changes detected"
          fi
      - name: Commit changes to repository
        run: |
          if ! git diff --quiet; then
            git add .
            git commit -m "Sync Dictionarry-Hub/database (excluding workflows)"
            git push origin main
          else
            echo "No changes to commit"
          fi
